blank_issues_enabled: false
contact_links:
  - name: Questions and Community Support
    url: https://stackoverflow.com/questions/tagged/spring-ai
    about: Please ask and answer questions on StackOverflow with the spring-ai tag
